import type { AchievementProgress } from '@markec/community.entities.achievement';

export const mockAchievements: AchievementProgress[] = [
  {
    id: `vrsic-conqueror`,
    name: `Vršič Conqueror`,
    description: `Complete the legendary Vršič Pass with 50 hairpin turns.`,
    icon: `🏔️`,
    unlocked: true,
    progressPct: 100,
    unlockedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: `1000-km-klub`,
    name: `1000 km Klub`,
    description: `Ride a total of 1,000 km across all your logged routes.`,
    icon: `🛣️`,
    unlocked: true,
    progressPct: 100,
    unlockedAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: `zgodnja-ptica`,
    name: `Zgodnja Ptica`,
    description: `Start a ride before 6 AM on three separate days.`,
    icon: `🌅`,
    unlocked: true,
    progressPct: 100,
    unlockedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: `kotor-master`,
    name: `Kotor Master`,
    description: `Navigate the serpentine road to Kotor Bay fortress.`,
    icon: `⚓`,
    unlocked: false,
    progressPct: 72,
    unlockedAt: undefined,
  },
  {
    id: `mokra-voznja`,
    name: `Mokra Vožnja`,
    description: `Complete a ride of at least 50 km in rainy conditions.`,
    icon: `🌧️`,
    unlocked: false,
    progressPct: 45,
    unlockedAt: undefined,
  },
  {
    id: `transfagarasan`,
    name: `Transfăgărășan`,
    description: `Conquer Romania\`s most dramatic mountain highway.`,
    icon: `🗻`,
    unlocked: false,
    progressPct: 30,
    unlockedAt: undefined,
  },
  {
    id: `balkanski-popotnik`,
    name: `Balkanski Popotnik`,
    description: `Ride through at least 5 different Balkan countries.`,
    icon: `🗺️`,
    unlocked: false,
    progressPct: 60,
    unlockedAt: undefined,
  },
  {
    id: `30-dnevna-serija`,
    name: `30-dnevna Serija`,
    description: `Log at least one ride every day for 30 consecutive days.`,
    icon: `📅`,
    unlocked: false,
    progressPct: 13,
    unlockedAt: undefined,
  },
  {
    id: `twisty-rider`,
    name: `Twisty Rider`,
    description: `Complete 10 routes rated as highly twisty by the community.`,
    icon: `🌀`,
    unlocked: false,
    progressPct: 80,
    unlockedAt: undefined,
  },
  {
    id: `cestni-bratec`,
    name: `Cestni Bratec`,
    description: `Join 5 group rides organised by other community members.`,
    icon: `🤝`,
    unlocked: false,
    progressPct: 40,
    unlockedAt: undefined,
  },
  {
    id: `pomocnik-skupnosti`,
    name: `Pomočnik Skupnosti`,
    description: `Report fuel prices at 10 different stations.`,
    icon: `⛽`,
    unlocked: false,
    progressPct: 20,
    unlockedAt: undefined,
  },
  {
    id: `stroski-pod-kontrolo`,
    name: `Stroški pod kontrolo`,
    description: `Track your fuel costs for an entire month without a gap.`,
    icon: `💰`,
    unlocked: false,
    progressPct: 5,
    unlockedAt: undefined,
  },
];

export const mockAchievementsAllUnlocked: AchievementProgress[] = mockAchievements.map((a) => ({
  ...a,
  unlocked: true,
  progressPct: 100,
  unlockedAt: a.unlockedAt ?? Date.now() - 1000 * 60 * 60 * 24 * 2,
}));

export const mockAchievementsAllLocked: AchievementProgress[] = mockAchievements.map((a) => ({
  ...a,
  unlocked: false,
  progressPct: a.progressPct < 100 ? a.progressPct : 0,
  unlockedAt: undefined,
}));
