/**
 * Static seed data used on first boot. Re-uses the same shape as the GraphQL
 * Hazard / SpeedCamera / BorderCrossing types.
 */

export const hazardSeeds = [
  {
    id: 'hz-seed-1',
    type: 'pothole',
    lat: 43.8563,
    lng: 18.4131,
    reportedAt: Date.now() - 1000 * 60 * 35,
    reportedBy: 'seed',
    confirmedCount: 4,
  },
  {
    id: 'hz-seed-2',
    type: 'ice',
    lat: 46.0569,
    lng: 14.5058,
    reportedAt: Date.now() - 1000 * 60 * 120,
    reportedBy: 'seed',
    confirmedCount: 2,
  },
  {
    id: 'hz-seed-3',
    type: 'animal',
    lat: 45.815,
    lng: 15.9819,
    reportedAt: Date.now() - 1000 * 60 * 12,
    reportedBy: 'seed',
    confirmedCount: 1,
  },
  {
    id: 'hz-seed-4',
    type: 'oil',
    lat: 44.7866,
    lng: 20.4489,
    reportedAt: Date.now() - 1000 * 60 * 60 * 3,
    reportedBy: 'seed',
    confirmedCount: 6,
  },
  {
    id: 'hz-seed-5',
    type: 'construction',
    lat: 42.4304,
    lng: 19.2594,
    reportedAt: Date.now() - 1000 * 60 * 60 * 5,
    reportedBy: 'seed',
    confirmedCount: 3,
  },
  {
    id: 'hz-seed-6',
    type: 'flood',
    lat: 42.6629,
    lng: 21.1655,
    reportedAt: Date.now() - 1000 * 60 * 60 * 12,
    reportedBy: 'seed',
    confirmedCount: 5,
  },
  {
    id: 'hz-seed-7',
    type: 'landslide',
    lat: 43.3438,
    lng: 17.808,
    reportedAt: Date.now() - 1000 * 60 * 60 * 24,
    reportedBy: 'seed',
    confirmedCount: 7,
  },
  {
    id: 'hz-seed-8',
    type: 'camera',
    lat: 41.9981,
    lng: 21.4254,
    reportedAt: Date.now() - 1000 * 60 * 60 * 2,
    reportedBy: 'seed',
    confirmedCount: 8,
  },
];

export const speedCameraSeeds = [
  { id: 'sc-1', lat: 46.0419, lng: 14.4762, speedLimit: 50, type: 'fixed', country: 'SI' },
  { id: 'sc-2', lat: 45.815, lng: 15.9819, speedLimit: 70, type: 'fixed', country: 'HR' },
  { id: 'sc-3', lat: 44.8125, lng: 20.4612, speedLimit: 60, type: 'average', country: 'RS' },
  { id: 'sc-4', lat: 42.6977, lng: 23.3219, speedLimit: 50, type: 'fixed', country: 'BG' },
  { id: 'sc-5', lat: 44.4268, lng: 26.1025, speedLimit: 80, type: 'fixed', country: 'RO' },
  { id: 'sc-6', lat: 43.8563, lng: 18.4131, speedLimit: 50, type: 'mobile', country: 'BA' },
  { id: 'sc-7', lat: 42.4411, lng: 19.2636, speedLimit: 60, type: 'fixed', country: 'ME' },
  { id: 'sc-8', lat: 41.9981, lng: 21.4254, speedLimit: 50, type: 'fixed', country: 'MK' },
  { id: 'sc-9', lat: 41.3275, lng: 19.8187, speedLimit: 60, type: 'fixed', country: 'AL' },
  { id: 'sc-10', lat: 42.6629, lng: 21.1655, speedLimit: 50, type: 'fixed', country: 'XK' },
  { id: 'sc-11', lat: 46.5547, lng: 15.6459, speedLimit: 70, type: 'average', country: 'SI' },
  { id: 'sc-12', lat: 45.328, lng: 14.4422, speedLimit: 50, type: 'fixed', country: 'HR' },
  { id: 'sc-13', lat: 45.2671, lng: 19.8335, speedLimit: 50, type: 'fixed', country: 'RS' },
  { id: 'sc-14', lat: 42.1417, lng: 24.7499, speedLimit: 60, type: 'mobile', country: 'BG' },
  { id: 'sc-15', lat: 46.7712, lng: 23.6236, speedLimit: 70, type: 'fixed', country: 'RO' },
  { id: 'sc-16', lat: 44.5366, lng: 18.6735, speedLimit: 60, type: 'fixed', country: 'BA' },
  { id: 'sc-17', lat: 42.4304, lng: 18.7705, speedLimit: 50, type: 'fixed', country: 'ME' },
  { id: 'sc-18', lat: 42.0064, lng: 20.9714, speedLimit: 60, type: 'mobile', country: 'MK' },
  { id: 'sc-19', lat: 42.0683, lng: 19.5024, speedLimit: 50, type: 'fixed', country: 'AL' },
  { id: 'sc-20', lat: 42.8826, lng: 20.8689, speedLimit: 60, type: 'fixed', country: 'XK' },
];

export const borderCrossingSeeds = [
  {
    id: 'bc-1',
    name: 'Šentilj',
    countryFrom: 'SI',
    countryTo: 'AT',
    documents: ['Osebna izkaznica', 'Potni list'],
    vignetteRequired: true,
    avgWaitMin: 5,
    tips: 'Vinjeta obvezna za Avstrijo. Kupite jo pred mejo.',
  },
  {
    id: 'bc-2',
    name: 'Karlovac',
    countryFrom: 'HR',
    countryTo: 'SI',
    documents: ['Osebna izkaznica'],
    vignetteRequired: true,
    avgWaitMin: 10,
    tips: 'Slovenska vinjeta obvezna.',
  },
  {
    id: 'bc-3',
    name: 'Gruškovje',
    countryFrom: 'SI',
    countryTo: 'HR',
    documents: ['Osebna izkaznica'],
    vignetteRequired: false,
    avgWaitMin: 15,
    tips: 'Daljše čakanje v poletni sezoni.',
  },
  {
    id: 'bc-4',
    name: 'Mostar',
    countryFrom: 'BA',
    countryTo: 'HR',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 20,
    tips: 'Mejni prehod z mejno kontrolo (ne-Schengen).',
  },
  {
    id: 'bc-5',
    name: 'Debeli Brijeg',
    countryFrom: 'ME',
    countryTo: 'HR',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 25,
    tips: 'Lahko zelo dolge vrste v poletnih mesecih.',
  },
  {
    id: 'bc-6',
    name: 'Kalotina',
    countryFrom: 'BG',
    countryTo: 'RS',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 30,
    tips: 'Glavni cestni prehod med BG in RS.',
  },
  {
    id: 'bc-7',
    name: 'Iași',
    countryFrom: 'RO',
    countryTo: 'MD',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 40,
    tips: 'Mejna kontrola pri vstopu v Moldavijo.',
  },
  {
    id: 'bc-8',
    name: 'Tabanovce',
    countryFrom: 'MK',
    countryTo: 'RS',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 15,
    tips: 'Standardni prehod, redko zastoji.',
  },
  {
    id: 'bc-9',
    name: 'Hani i Hotit',
    countryFrom: 'AL',
    countryTo: 'ME',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 20,
    tips: 'Lepa pot, priporočen za motoriste.',
  },
  {
    id: 'bc-10',
    name: 'Merdare',
    countryFrom: 'XK',
    countryTo: 'RS',
    documents: ['Potni list'],
    vignetteRequired: false,
    avgWaitMin: 25,
    tips: 'Občasno daljše vrste, vzemite zavarovanje.',
  },
];
