import type { FuelPriceReport, CountryAverage } from './fuel-price-report-type.js';

const now = Date.now();
const hour = 3_600_000;

export const mockFuelPriceReports: FuelPriceReport[] = [
  {
    id: `rpt-001`,
    country: `SI`,
    brand: `Petrol`,
    petrolEur: 1.529,
    dieselEur: 1.489,
    location: `Ljubljana – BTC`,
    reportedAt: now - 2 * hour,
    confirms: 12,
  },
  {
    id: `rpt-002`,
    country: `SI`,
    brand: `MOL`,
    petrolEur: 1.539,
    dieselEur: 1.499,
    location: `Maribor – Tezno`,
    reportedAt: now - 4 * hour,
    confirms: 7,
  },
  {
    id: `rpt-003`,
    country: `HR`,
    brand: `INA`,
    petrolEur: 1.479,
    dieselEur: 1.439,
    location: `Zagreb – Jankomir`,
    reportedAt: now - 1 * hour,
    confirms: 18,
  },
  {
    id: `rpt-004`,
    country: `HR`,
    brand: `Tifon`,
    petrolEur: 1.489,
    dieselEur: 1.449,
    location: `Split – Solin`,
    reportedAt: now - 3 * hour,
    confirms: 5,
  },
  {
    id: `rpt-005`,
    country: `BA`,
    brand: `Energopetrol`,
    petrolEur: 1.299,
    dieselEur: 1.259,
    location: `Sarajevo – Ilidža`,
    reportedAt: now - 5 * hour,
    confirms: 9,
  },
  {
    id: `rpt-006`,
    country: `RS`,
    brand: `NIS`,
    petrolEur: 1.389,
    dieselEur: 1.349,
    location: `Beograd – Autokomanda`,
    reportedAt: now - 2 * hour,
    confirms: 22,
  },
  {
    id: `rpt-007`,
    country: `RS`,
    brand: `Gazprom`,
    petrolEur: 1.399,
    dieselEur: 1.359,
    location: `Novi Sad – Bulevar`,
    reportedAt: now - 6 * hour,
    confirms: 4,
  },
  {
    id: `rpt-008`,
    country: `ME`,
    brand: `Jugopetrol`,
    petrolEur: 1.459,
    dieselEur: 1.419,
    location: `Podgorica – Zabjelo`,
    reportedAt: now - 3 * hour,
    confirms: 11,
  },
  {
    id: `rpt-009`,
    country: `MK`,
    brand: `Makpetrol`,
    petrolEur: 1.319,
    dieselEur: 1.279,
    location: `Skopje – Aerodrom`,
    reportedAt: now - 7 * hour,
    confirms: 6,
  },
  {
    id: `rpt-010`,
    country: `AL`,
    brand: `Kastrati`,
    petrolEur: 1.559,
    dieselEur: 1.509,
    location: `Tirana – Autostrada`,
    reportedAt: now - 4 * hour,
    confirms: 3,
  },
  {
    id: `rpt-011`,
    country: `BG`,
    brand: `Lukoil`,
    petrolEur: 1.349,
    dieselEur: 1.309,
    location: `Sofia – Tsarigradsko`,
    reportedAt: now - 1 * hour,
    confirms: 15,
  },
  {
    id: `rpt-012`,
    country: `RO`,
    brand: `OMV Petrom`,
    petrolEur: 1.429,
    dieselEur: 1.379,
    location: `București – Pipera`,
    reportedAt: now - 5 * hour,
    confirms: 8,
  },
  {
    id: `rpt-013`,
    country: `GR`,
    brand: `BP`,
    petrolEur: 1.729,
    dieselEur: 1.589,
    location: `Thessaloniki – IKEA`,
    reportedAt: now - 2 * hour,
    confirms: 14,
  },
];

export const mockCountryAverages: CountryAverage[] = [
  {
    country: `SI`,
    avgPetrolEur: 1.534,
    avgDieselEur: 1.494,
    reportCount: 47,
    lastReportedAt: now - 2 * hour,
  },
  {
    country: `HR`,
    avgPetrolEur: 1.484,
    avgDieselEur: 1.444,
    reportCount: 63,
    lastReportedAt: now - 1 * hour,
  },
  {
    country: `BA`,
    avgPetrolEur: 1.299,
    avgDieselEur: 1.259,
    reportCount: 28,
    lastReportedAt: now - 5 * hour,
  },
  {
    country: `RS`,
    avgPetrolEur: 1.394,
    avgDieselEur: 1.354,
    reportCount: 55,
    lastReportedAt: now - 2 * hour,
  },
  {
    country: `ME`,
    avgPetrolEur: 1.459,
    avgDieselEur: 1.419,
    reportCount: 19,
    lastReportedAt: now - 3 * hour,
  },
  {
    country: `MK`,
    avgPetrolEur: 1.319,
    avgDieselEur: 1.279,
    reportCount: 14,
    lastReportedAt: now - 7 * hour,
  },
  {
    country: `AL`,
    avgPetrolEur: 1.559,
    avgDieselEur: 1.509,
    reportCount: 11,
    lastReportedAt: now - 4 * hour,
  },
  {
    country: `BG`,
    avgPetrolEur: 1.349,
    avgDieselEur: 1.309,
    reportCount: 38,
    lastReportedAt: now - 1 * hour,
  },
  {
    country: `RO`,
    avgPetrolEur: 1.429,
    avgDieselEur: 1.379,
    reportCount: 31,
    lastReportedAt: now - 5 * hour,
  },
  {
    country: `GR`,
    avgPetrolEur: 1.729,
    avgDieselEur: 1.589,
    reportCount: 42,
    lastReportedAt: now - 2 * hour,
  },
];
