import type { CommunityRoute } from '@markec/community.entities.community-route';

export const mockCommunityRoutes: CommunityRoute[] = [
  {
    id: `route-1`,
    name: `Skrita Logarska`,
    author: `Luka Horvat`,
    country: `SI`,
    distanceKm: 142,
    durationSec: 18000,
    difficulty: `medium`,
    rating: 4.8,
    likes: 312,
    geometry: [
      { lat: 46.3833, lng: 14.6333 },
      { lat: 46.4, lng: 14.7 },
    ],
  },
  {
    id: `route-2`,
    name: `Durmitor Zanka`,
    author: `Marko Petrović`,
    country: `ME`,
    distanceKm: 198,
    durationSec: 25200,
    difficulty: `hard`,
    rating: 4.6,
    likes: 247,
    geometry: [
      { lat: 43.15, lng: 19.0 },
      { lat: 43.2, lng: 19.1 },
    ],
  },
  {
    id: `route-3`,
    name: `Plitvička Jezera`,
    author: `Ivan Kovač`,
    country: `HR`,
    distanceKm: 87,
    durationSec: 10800,
    difficulty: `easy`,
    rating: 4.9,
    likes: 489,
    geometry: [
      { lat: 44.88, lng: 15.62 },
      { lat: 44.9, lng: 15.65 },
    ],
  },
  {
    id: `route-4`,
    name: `Pirin Enduro`,
    author: `Nikola Dimitrov`,
    country: `BG`,
    distanceKm: 215,
    durationSec: 28800,
    difficulty: `expert`,
    rating: 4.5,
    likes: 178,
    geometry: [
      { lat: 41.75, lng: 23.4 },
      { lat: 41.8, lng: 23.5 },
    ],
  },
  {
    id: `route-5`,
    name: `Transfăgărășan Ekspres`,
    author: `Bogdan Ionescu`,
    country: `RO`,
    distanceKm: 320,
    durationSec: 36000,
    difficulty: `hard`,
    rating: 4.7,
    likes: 391,
    geometry: [
      { lat: 45.6, lng: 24.6 },
      { lat: 45.65, lng: 24.7 },
    ],
  },
  {
    id: `route-6`,
    name: `Olimp Obalna Pot`,
    author: `Aris Papadopoulos`,
    country: `GR`,
    distanceKm: 165,
    durationSec: 21600,
    difficulty: `medium`,
    rating: 4.4,
    likes: 203,
    geometry: [
      { lat: 40.08, lng: 22.35 },
      { lat: 40.1, lng: 22.4 },
    ],
  },
  {
    id: `route-7`,
    name: `Sarajevo Panorama`,
    author: `Emir Begić`,
    country: `BA`,
    distanceKm: 95,
    durationSec: 12600,
    difficulty: `easy`,
    rating: 4.3,
    likes: 156,
    geometry: [
      { lat: 43.85, lng: 18.39 },
      { lat: 43.87, lng: 18.42 },
    ],
  },
  {
    id: `route-8`,
    name: `Prokletije Avantura`,
    author: `Arben Krasniqi`,
    country: `AL`,
    distanceKm: 278,
    durationSec: 32400,
    difficulty: `expert`,
    rating: 4.6,
    likes: 134,
    geometry: [
      { lat: 42.4, lng: 20.0 },
      { lat: 42.45, lng: 20.05 },
    ],
  },
];
