import type { Ride } from './ride-type';

const now = Date.now();
const DAY = 86_400_000;

export const mockRides: Ride[] = [
  {
    id: `ride-1`,
    userId: `user-1`,
    startedAt: now - 1 * DAY,
    endedAt: now - 1 * DAY + 5_400_000,
    distanceKm: 142.3,
    durationSec: 5400,
    maxSpeedKmh: 187,
    avgSpeedKmh: 94.9,
    climbM: 1240,
    descentM: 1180,
    twistinessScore: 82,
    name: `Alpine Pass Sprint`,
    notes: `Perfect weather, great grip on the north face.`,
  },
  {
    id: `ride-2`,
    userId: `user-1`,
    startedAt: now - 3 * DAY,
    endedAt: now - 3 * DAY + 3_600_000,
    distanceKm: 78.5,
    durationSec: 3600,
    maxSpeedKmh: 156,
    avgSpeedKmh: 78.5,
    climbM: 620,
    descentM: 590,
    twistinessScore: 65,
    name: `Coast Road Cruise`,
    notes: `Light traffic, beautiful sea views.`,
  },
  {
    id: `ride-3`,
    userId: `user-1`,
    startedAt: now - 5 * DAY,
    endedAt: now - 5 * DAY + 7_200_000,
    distanceKm: 210.1,
    durationSec: 7200,
    maxSpeedKmh: 212,
    avgSpeedKmh: 105,
    climbM: 2100,
    descentM: 2050,
    twistinessScore: 91,
    name: `Dolomites Loop`,
    notes: `Challenging but rewarding. Passo Pordoi was stunning.`,
  },
  {
    id: `ride-4`,
    userId: `user-1`,
    startedAt: now - 8 * DAY,
    endedAt: now - 8 * DAY + 2_700_000,
    distanceKm: 55.2,
    durationSec: 2700,
    maxSpeedKmh: 134,
    avgSpeedKmh: 73.6,
    climbM: 310,
    descentM: 295,
    twistinessScore: 44,
    name: `Morning Warm-Up`,
  },
  {
    id: `ride-5`,
    userId: `user-1`,
    startedAt: now - 12 * DAY,
    endedAt: now - 12 * DAY + 9_000_000,
    distanceKm: 318.7,
    durationSec: 9000,
    maxSpeedKmh: 231,
    avgSpeedKmh: 127.5,
    climbM: 3400,
    descentM: 3380,
    twistinessScore: 97,
    name: `Gran Fondo Moto`,
    notes: `Epic day. Crossed three mountain passes.`,
  },
  {
    id: `ride-6`,
    userId: `user-1`,
    startedAt: now - 15 * DAY,
    endedAt: now - 15 * DAY + 4_500_000,
    distanceKm: 99.8,
    durationSec: 4500,
    maxSpeedKmh: 168,
    avgSpeedKmh: 79.8,
    climbM: 870,
    descentM: 840,
    twistinessScore: 73,
    name: `Forest Trail Run`,
  },
  {
    id: `ride-7`,
    userId: `user-1`,
    startedAt: now - 18 * DAY,
    endedAt: now - 18 * DAY + 1_800_000,
    distanceKm: 34.1,
    durationSec: 1800,
    maxSpeedKmh: 112,
    avgSpeedKmh: 68.2,
    climbM: 180,
    descentM: 175,
    twistinessScore: 38,
    name: `Quick Evening Lap`,
  },
  {
    id: `ride-8`,
    userId: `user-1`,
    startedAt: now - 22 * DAY,
    endedAt: now - 22 * DAY + 6_300_000,
    distanceKm: 175.4,
    durationSec: 6300,
    maxSpeedKmh: 198,
    avgSpeedKmh: 100.2,
    climbM: 1680,
    descentM: 1650,
    twistinessScore: 88,
    name: `Black Forest Blast`,
    notes: `Overcast but dry. Roads were empty.`,
  },
];

export const mockRidesSparse: Ride[] = mockRides.slice(0, 2);
