import type { CountryBrowserRoad } from './country-browser-road-type.js';

export const mockCountryBrowserRoads: CountryBrowserRoad[] = [
  {
    id: `si-vrsic`,
    name: `Vršič Pass`,
    country: `SI`,
    type: `Pass`,
    lengthKm: 25.4,
    rating: 9.2,
    difficulty: `Hard`,
  },
  {
    id: `si-soca`,
    name: `Soča Valley Route`,
    country: `SI`,
    type: `Forest`,
    lengthKm: 48.2,
    rating: 8.5,
    difficulty: `Moderate`,
  },
  {
    id: `si-predil`,
    name: `Predil Pass`,
    country: `SI`,
    type: `Pass`,
    lengthKm: 18.7,
    rating: 8.1,
    difficulty: `Moderate`,
  },
  {
    id: `hr-adriatic`,
    name: `Adriatic Coastal Road`,
    country: `HR`,
    type: `Coastal`,
    lengthKm: 178.5,
    rating: 8.7,
    difficulty: `Easy`,
  },
  {
    id: `hr-plitvice`,
    name: `Plitvice Lakes Loop`,
    country: `HR`,
    type: `Forest`,
    lengthKm: 62.3,
    rating: 8.3,
    difficulty: `Easy`,
  },
  {
    id: `hr-biokovo`,
    name: `Biokovo Mountain Road`,
    country: `HR`,
    type: `Pass`,
    lengthKm: 34.1,
    rating: 9.0,
    difficulty: `Hard`,
  },
  {
    id: `ro-transfagarasan`,
    name: `Transfăgărășan`,
    country: `RO`,
    type: `Pass`,
    lengthKm: 90.0,
    rating: 9.8,
    difficulty: `Expert`,
  },
  {
    id: `ro-transalpina`,
    name: `Transalpina`,
    country: `RO`,
    type: `Pass`,
    lengthKm: 148.0,
    rating: 9.4,
    difficulty: `Hard`,
  },
  {
    id: `me-kotor`,
    name: `Kotor Serpentine`,
    country: `ME`,
    type: `Serpentine`,
    lengthKm: 22.8,
    rating: 9.1,
    difficulty: `Hard`,
  },
  {
    id: `me-durmitor`,
    name: `Durmitor Ring Road`,
    country: `ME`,
    type: `Pass`,
    lengthKm: 55.0,
    rating: 8.9,
    difficulty: `Expert`,
  },
  {
    id: `gr-zagori`,
    name: `Zagori Mountain Roads`,
    country: `GR`,
    type: `Forest`,
    lengthKm: 74.5,
    rating: 8.6,
    difficulty: `Moderate`,
  },
  {
    id: `ba-neretva`,
    name: `Neretva Canyon Route`,
    country: `BA`,
    type: `Coastal`,
    lengthKm: 88.0,
    rating: 8.4,
    difficulty: `Moderate`,
  },
];
