import type { TourCardTour } from '@markec/balkan-roads.ui.tour-card';

export const mockExploreTours: TourCardTour[] = [
  {
    id: `tour-vrsic`,
    name: `Vršič Pass Loop`,
    country: `SI`,
    flag: `🇸🇮`,
    distanceKm: 142,
    rating: 4.9,
    difficulty: `Moderate`,
    description: `Legendarni prelaz Vršič s 50 ovinki skozi Julijske Alpe. Ena najlepših gorskih cest v Evropi z razgledom na Triglav.`,
    waypoints: [
      { lat: 46.4386, lng: 13.7445, name: `Kranjska Gora` },
      { lat: 46.4308, lng: 13.7447, name: `Vršič vrh` },
      { lat: 46.3769, lng: 13.7189, name: `Trenta` },
    ],
  },
  {
    id: `tour-kotor`,
    name: `Kotorska serpentinska pot`,
    country: `ME`,
    flag: `🇲🇪`,
    distanceKm: 98,
    rating: 4.8,
    difficulty: `Hard`,
    description: `Dramatične serpentine nad Kotorskim zalivom z neverjetnimi razgledi na Jadransko morje in staro mestno jedro Kotorja.`,
    waypoints: [
      { lat: 42.4247, lng: 18.7712, name: `Kotor` },
      { lat: 42.4456, lng: 18.7234, name: `Lovćen vrh` },
      { lat: 42.3869, lng: 18.8123, name: `Budva` },
    ],
  },
  {
    id: `tour-transfagarasan`,
    name: `Transfăgărășan`,
    country: `RO`,
    flag: `🇷🇴`,
    distanceKm: 151,
    rating: 5.0,
    difficulty: `Hard`,
    description: `Romunska legenda — cesta, ki jo je Top Gear razglasil za najboljšo na svetu. Dramatični vzponi, tuneli in gorska jezera.`,
    waypoints: [
      { lat: 45.3547, lng: 24.6167, name: `Curtea de Argeș` },
      { lat: 45.5986, lng: 24.6167, name: `Balea Lac` },
      { lat: 45.7234, lng: 24.5678, name: `Sibiu` },
    ],
  },
  {
    id: `tour-plitvice`,
    name: `Plitvička jezera & Velebit`,
    country: `HR`,
    flag: `🇭🇷`,
    distanceKm: 187,
    rating: 4.7,
    difficulty: `Easy`,
    description: `Sproščena tura skozi hrvaški notranjost mimo Plitvičkih jezer in vzdolž veličastnega Velebita z razgledom na Jadran.`,
    waypoints: [
      { lat: 44.8654, lng: 15.6219, name: `Plitvice` },
      { lat: 44.5467, lng: 15.3456, name: `Gospić` },
      { lat: 44.1234, lng: 15.2345, name: `Zadar` },
    ],
  },
  {
    id: `tour-via-dinarica`,
    name: `Via Dinarica Highland`,
    country: `BA`,
    flag: `🇧🇦`,
    distanceKm: 234,
    rating: 4.6,
    difficulty: `Expert`,
    description: `Epska tura čez bosansko visokogorje po poti Via Dinarica. Divja narava, planinska sela in nepozabni razgledi na Dinaride.`,
    waypoints: [
      { lat: 43.8563, lng: 18.4131, name: `Sarajevo` },
      { lat: 43.7234, lng: 17.9876, name: `Bjelašnica` },
      { lat: 43.3456, lng: 17.8123, name: `Mostar` },
    ],
  },
  {
    id: `tour-olympus`,
    name: `Olimp & Meteore`,
    country: `GR`,
    flag: `🇬🇷`,
    distanceKm: 312,
    rating: 4.8,
    difficulty: `Moderate`,
    description: `Mitska tura od vznožja Olimpa do lebdečih samostanov Meteor. Grška pokrajina v vsej svoji veličini.`,
    waypoints: [
      { lat: 40.0853, lng: 22.3584, name: `Litochoro` },
      { lat: 39.9456, lng: 22.1234, name: `Olimp vrh` },
      { lat: 39.7123, lng: 21.6234, name: `Meteore` },
    ],
  },
];
