import { LeaderboardEntry } from '@markec/community.entities.leaderboard-entry';

/**
 * Mock leaderboard entries for testing and compositions.
 */
export const mockLeaderboardEntries: LeaderboardEntry[] = [
  LeaderboardEntry.from({
    rank: 1,
    userId: 'user-001',
    displayName: 'Marco Bianchi',
    country: 'IT',
    km: 4820.5,
    rides: 38,
    points: 9640,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 2,
    userId: 'user-002',
    displayName: 'Luka Horvat',
    country: 'SI',
    km: 4310.2,
    rides: 34,
    points: 8720,
    me: true,
  }),
  LeaderboardEntry.from({
    rank: 3,
    userId: 'user-003',
    displayName: 'Carlos Ruiz',
    country: 'ES',
    km: 3980.8,
    rides: 31,
    points: 7960,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 4,
    userId: 'user-004',
    displayName: 'Jan Novák',
    country: 'CZ',
    km: 3540.1,
    rides: 28,
    points: 7080,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 5,
    userId: 'user-005',
    displayName: 'Tomáš Kováč',
    country: 'SK',
    km: 3120.4,
    rides: 25,
    points: 6240,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 6,
    userId: 'user-006',
    displayName: 'Ana Petrović',
    country: 'RS',
    km: 2890.7,
    rides: 23,
    points: 5780,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 7,
    userId: 'user-007',
    displayName: 'Matej Kovač',
    country: 'HR',
    km: 2650.3,
    rides: 21,
    points: 5300,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 8,
    userId: 'user-008',
    displayName: 'Petra Novak',
    country: 'SI',
    km: 2410.9,
    rides: 19,
    points: 4820,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 9,
    userId: 'user-009',
    displayName: 'Stefan Müller',
    country: 'DE',
    km: 2180.6,
    rides: 17,
    points: 4360,
    me: false,
  }),
  LeaderboardEntry.from({
    rank: 10,
    userId: 'user-010',
    displayName: 'Iva Marković',
    country: 'BA',
    km: 1960.2,
    rides: 15,
    points: 3920,
    me: false,
  }),
];
