import type { ChallengeItem } from './challenge-item-type.js';

export const mockChallenges: ChallengeItem[] = [
  {
    id: `balkanski-tour`,
    name: `Balkanski Tour`,
    description: `Complete a 500 km ride through at least 3 Balkan countries within 30 days.`,
    icon: `🏆`,
    points: 500,
    status: `active`,
    endsAt: Date.now() + 1000 * 60 * 60 * 24 * 12,
    participants: 142,
    joined: true,
    progressPct: 68,
  },
  {
    id: `vrsic-50-serpentin`,
    name: `Vršič 50 Serpentin`,
    description: `Ride all 50 hairpin turns of the Vršič mountain pass in a single session.`,
    icon: `🌀`,
    points: 300,
    status: `active`,
    endsAt: Date.now() + 1000 * 60 * 60 * 24 * 5,
    participants: 87,
    joined: false,
    progressPct: 0,
  },
  {
    id: `marec-na-motorju`,
    name: `Marec Na Motorju`,
    description: `Log at least 10 rides during the month of March to earn the seasonal badge.`,
    icon: `📅`,
    points: 200,
    status: `active`,
    endsAt: Date.now() + 1000 * 60 * 60 * 24 * 3,
    participants: 310,
    joined: true,
    progressPct: 40,
  },
  {
    id: `jutranja-serija`,
    name: `Jutranja Serija`,
    description: `Start 7 consecutive morning rides before 8 AM to prove you are a true dawn rider.`,
    icon: `🌅`,
    points: 150,
    status: `active`,
    endsAt: Date.now() + 1000 * 60 * 60 * 24 * 18,
    participants: 56,
    joined: false,
    progressPct: 0,
  },
];
